### ISSUE TITLE
Wrong function call

### ISSUE THREAD

**Issue by ivoneijr** [4alltecnologia/node-es6-seed#18]
https://github.com/4alltecnologia/node-es6-seed/blob/eb9908add2927caf169920d6695f311d92afc03a/src/config/LoggerConfig.js#L114

**getLevelByStatusCode** function doesn't exists in **Logger** class, this line will raise:

```
TypeError: Logger.getLevelByStatusCode is not a function
    at requestDebugFormatter (/Users/ivoneijr/projects/node-es6-seed/src/config/LoggerConfig.js:114:22)
    at Request.<anonymous> (/Users/ivoneijr/projects/node-es6-seed/node_modules/request-debug/index.js:38:11)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.start (/Users/ivoneijr/projects/node-es6-seed/node_modules/request/request.js:865:8)
    at Request.end (/Users/ivoneijr/projects/node-es6-seed/node_modules/request/request.js:1525:10)
    at end (/Users/ivoneijr/projects/node-es6-seed/node_modules/request/request.js:567:14)
    at Immediate._onImmediate (/Users/ivoneijr/projects/node-es6-seed/node_modules/request/request.js:581:7)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
[nodemon] app crashed - waiting for file changes before starting...
```

To fix this call function in LoggerConfig context.

**Comment by henrique502** [comment]
Thank you, fix applied.
